//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetUserManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AssetManagementEntities : DbContext
    {
        public AssetManagementEntities()
            : base("name=AssetManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Customer_data> Customer_data { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Site_Asset> Site_Asset { get; set; }
        public virtual DbSet<Tbl_AssestMaster> Tbl_AssestMaster { get; set; }
        public virtual DbSet<Tbl_UserMaster> Tbl_UserMaster { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    
        public virtual ObjectResult<USP_GetAssetDetails_Result> USP_GetAssetDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetAssetDetails_Result>("USP_GetAssetDetails");
        }
    }
}
