//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetUserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_data
    {
        public int Customer_id { get; set; }
        public string Customer_Name { get; set; }
        public string Credit_card_number { get; set; }
        public byte[] Credit_card_number_encrypt { get; set; }
    }
}
