//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetUserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Asset
    {
        public string Site { get; set; }
        public string Facility { get; set; }
        public string AssetType { get; set; }
        public string Model { get; set; }
        public string Asset { get; set; }
        public string AssetDesc { get; set; }
        public int AssetId { get; set; }
    }
}
